# Generated by Django 5.0.2 on 2025-05-17 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='author',
            new_name='author_name',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='abstract',
        ),
        migrations.AddField(
            model_name='paper',
            name='address_line1',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='paper',
            name='address_line2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='paper',
            name='area_of_research',
            field=models.CharField(choices=[('cs', 'Computer Science'), ('ee', 'Electrical Engineering'), ('me', 'Mechanical Engineering'), ('ce', 'Civil Engineering'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='paper',
            name='city',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='paper',
            name='country',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='paper',
            name='institution',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='mobile',
            field=models.CharField(default='N/A', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='pincode',
            field=models.CharField(default='000000', max_length=20),
        ),
        migrations.AddField(
            model_name='paper',
            name='prev_paper',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='paper',
            name='state',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.CreateModel(
            name='CoAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coauthors', to='journal.paper')),
            ],
        ),
    ]
