# Generated by Django 5.0.2 on 2025-05-18 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_paper_area_of_research'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('issue', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ArchivePaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='archive_papers/')),
                ('read_more_url', models.URLField(blank=True)),
                ('archive_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='journal.archiveissue')),
            ],
        ),
    ]
