# Generated by Django 5.0.2 on 2025-05-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_archiveissue_archivepaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
