# Generated by Django 5.0.2 on 2025-06-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_paper_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='reference_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='saved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='saved_for_future',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paper',
            name='address_line1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='paper',
            name='area_of_research',
            field=models.CharField(choices=[('engineering', 'Engineering'), ('science', 'Science'), ('technology', 'Technology'), ('medical', 'Medical'), ('management', 'Management'), ('other', 'Other')], default='engineering', max_length=50),
        ),
        migrations.AlterField(
            model_name='paper',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paper',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paper',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='paper',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
